### ISSUE TITLE
not working with me...

### ISSUE THREAD

**Issue by b4sh1t1** [cchash/BatchGuard#1]
hello,
it's not working with me, can we talk on weechat please to check it ?

**Comment by cchash** [comment]
Does the application not work or does the outputted batch file not work?

**Comment by b4sh1t1** [comment]
will try, can i talk to you on [weechat](oriental.infosec@gmail.com) ?

**Comment by cchash** [comment]
Do you mean WeChat or IRC?

**Comment by b4sh1t1** [comment]
on mail possible ? google chat

**Comment by cchash** [comment]
sure, i messaged you on google chat
